// flow-typed signature: a1db9db09c680faa4855f8577c80740a
// flow-typed version: <<STUB>>/path-to-regexp_v^1.5.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'path-to-regexp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'path-to-regexp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'path-to-regexp/index' {
  declare module.exports: $Exports<'path-to-regexp'>;
}
declare module 'path-to-regexp/index.js' {
  declare module.exports: $Exports<'path-to-regexp'>;
}
